name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_agent:
    env:
      working-directory: ./agent

    runs-on: ubuntu-latest

    steps:
    # we don't need checkout because of 'context' in docker/build-push-action
    # https://github.com/marketplace/actions/build-and-push-docker-images#git-context
    # - uses: actions/checkout@v3  
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}        

    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        context: "https://github.com/${{ github.repository }}.git#${{ github.sha }}:agent"
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        tags: kanosaki/fdb_manager_agent:latest

